### ISSUE TITLE
Specs fail with TRR 0.8.0.pre3

### ISSUE THREAD

**Issue by rainkinz** [svenfuchs/rdom#1]
Running tests gives:

MissingSourceFile: no such file to load -- v8/to

**Comment by cowboyd** [comment]
rdom had a lot of workarounds for issues with TRR. If I remember correctly, it monkey patches some internals to make up for deficiencies in 0.7.5

**Comment by rainkinz** [comment]
Yes, I see that. I was having a go at fixing it myself, but I'm stuck on an issue in the Portal class where rdom seems to be passing it a string "" (at least I think that's what's happening), which doesn't have a superclass method....

**Comment by cowboyd** [comment]
do you have a link to a source file or a gist maybe?
